;  ---------------------------------------------
;  --- Definizione del modulo e dei template ---
;  ---------------------------------------------
(defmodule AGENT (import MAIN ?ALL) (import ENV ?ALL) (export ?ALL))


(deftemplate my-cell
	(slot x)
	(slot y)
	(slot content (allowed-values unknown water boat next-guess))
)
(deftemplate navy
	(slot submarines)
	(slot destroyers)
	(slot cruisers)
	(slot battleship)
)
(deftemplate max_n
	(slot maxr)
	(slot indexr)
	(slot maxc)
	(slot indexc)
)
(deftemplate n_actions
	(slot n_guess)
	(slot n_fire)
)


(deffacts utils-stats
	(max_n (maxr 0) (indexr 0) (maxc 0) (indexc 0))
)

(deffacts actions
	(n_actions (n_guess 0) (n_fire 0))
)

(deffacts my_battle_field
	(my-cell (x 0) (y 0) (content unknown) )
	(my-cell (x 0) (y 1) (content unknown) )
	(my-cell (x 0) (y 2) (content unknown) )
	(my-cell (x 0) (y 3) (content unknown) )
	(my-cell (x 0) (y 4) (content unknown) )
	(my-cell (x 0) (y 5) (content unknown) )
	(my-cell (x 0) (y 6) (content unknown) )
	(my-cell (x 0) (y 7) (content unknown) )
	(my-cell (x 0) (y 8) (content unknown) )
	(my-cell (x 0) (y 9) (content unknown) )
	(my-cell (x 1) (y 0) (content unknown) )
	(my-cell (x 1) (y 1) (content unknown) )
	(my-cell (x 1) (y 2) (content unknown) )
	(my-cell (x 1) (y 3) (content unknown) )
	(my-cell (x 1) (y 4) (content unknown) )
	(my-cell (x 1) (y 5) (content unknown) )
	(my-cell (x 1) (y 6) (content unknown) )
	(my-cell (x 1) (y 7) (content unknown) )
	(my-cell (x 1) (y 8) (content unknown) )
	(my-cell (x 1) (y 9) (content unknown) )
	(my-cell (x 2) (y 0) (content unknown) )
	(my-cell (x 2) (y 1) (content unknown) )
	(my-cell (x 2) (y 2) (content unknown) )
	(my-cell (x 2) (y 3) (content unknown) )
	(my-cell (x 2) (y 4) (content unknown) )
	(my-cell (x 2) (y 5) (content unknown) )
	(my-cell (x 2) (y 6) (content unknown) )
	(my-cell (x 2) (y 7) (content unknown) )
	(my-cell (x 2) (y 8) (content unknown) )
	(my-cell (x 2) (y 9) (content unknown) )
	(my-cell (x 3) (y 0) (content unknown) )
	(my-cell (x 3) (y 1) (content unknown) )
	(my-cell (x 3) (y 2) (content unknown) )
	(my-cell (x 3) (y 3) (content unknown) )
	(my-cell (x 3) (y 4) (content unknown) )
	(my-cell (x 3) (y 5) (content unknown) )
	(my-cell (x 3) (y 6) (content unknown) )
	(my-cell (x 3) (y 7) (content unknown) )
	(my-cell (x 3) (y 8) (content unknown) )
	(my-cell (x 3) (y 9) (content unknown) )
	(my-cell (x 4) (y 0) (content unknown) )
	(my-cell (x 4) (y 1) (content unknown) )
	(my-cell (x 4) (y 2) (content unknown) )
	(my-cell (x 4) (y 3) (content unknown) )
	(my-cell (x 4) (y 4) (content unknown) )
	(my-cell (x 4) (y 5) (content unknown) )
	(my-cell (x 4) (y 6) (content unknown) )
	(my-cell (x 4) (y 7) (content unknown) )
	(my-cell (x 4) (y 8) (content unknown) )
	(my-cell (x 4) (y 9) (content unknown) )
	(my-cell (x 5) (y 0) (content unknown) )
	(my-cell (x 5) (y 1) (content unknown) )
	(my-cell (x 5) (y 2) (content unknown) )
	(my-cell (x 5) (y 3) (content unknown) )
	(my-cell (x 5) (y 4) (content unknown) )
	(my-cell (x 5) (y 5) (content unknown) )
	(my-cell (x 5) (y 6) (content unknown) )
	(my-cell (x 5) (y 7) (content unknown) )
	(my-cell (x 5) (y 8) (content unknown) )
	(my-cell (x 5) (y 9) (content unknown) )
	(my-cell (x 6) (y 0) (content unknown) )
	(my-cell (x 6) (y 1) (content unknown) )
	(my-cell (x 6) (y 2) (content unknown) )
	(my-cell (x 6) (y 3) (content unknown) )
	(my-cell (x 6) (y 4) (content unknown) )
	(my-cell (x 6) (y 5) (content unknown) )
	(my-cell (x 6) (y 6) (content unknown) )
	(my-cell (x 6) (y 7) (content unknown) )
	(my-cell (x 6) (y 8) (content unknown) )
	(my-cell (x 6) (y 9) (content unknown) )
	(my-cell (x 7) (y 0) (content unknown) )
	(my-cell (x 7) (y 1) (content unknown) )
	(my-cell (x 7) (y 2) (content unknown) )
	(my-cell (x 7) (y 3) (content unknown) )
	(my-cell (x 7) (y 4) (content unknown) )
	(my-cell (x 7) (y 5) (content unknown) )
	(my-cell (x 7) (y 6) (content unknown) )
	(my-cell (x 7) (y 7) (content unknown) )
	(my-cell (x 7) (y 8) (content unknown) )
	(my-cell (x 7) (y 9) (content unknown) )
	(my-cell (x 8) (y 0) (content unknown) )
	(my-cell (x 8) (y 1) (content unknown) )
	(my-cell (x 8) (y 2) (content unknown) )
	(my-cell (x 8) (y 3) (content unknown) )
	(my-cell (x 8) (y 4) (content unknown) )
	(my-cell (x 8) (y 5) (content unknown) )
	(my-cell (x 8) (y 6) (content unknown) )
	(my-cell (x 8) (y 7) (content unknown) )
	(my-cell (x 8) (y 8) (content unknown) )
	(my-cell (x 8) (y 9) (content unknown) )
	(my-cell (x 9) (y 0) (content unknown) )
	(my-cell (x 9) (y 1) (content unknown) )
	(my-cell (x 9) (y 2) (content unknown) )
	(my-cell (x 9) (y 3) (content unknown) )
	(my-cell (x 9) (y 4) (content unknown) )
	(my-cell (x 9) (y 5) (content unknown) )
	(my-cell (x 9) (y 6) (content unknown) )
	(my-cell (x 9) (y 7) (content unknown) )
	(my-cell (x 9) (y 8) (content unknown) )
	(my-cell (x 9) (y 9) (content unknown) )
)

; (not (k-per-row (row ?r2&:(new ?r2 ?r)) (num ?n2 &:(> ?n2 ?n))))  ; calcola il valore massimo di n per k-per-row
; calcolarlo in questo mdoo per evitare di tenere traccia dei massimi con utils stats. In sostanza va calcolato nei posti in cui serve, fire e guess

; ------------------------------ UTILS ------------------------------
(defrule check-max-row (declare (salience 20))
	?max <- (max_n (maxr ?mr) (indexr ?idxr))
	(k-per-row (row ?r) (num ?n &:(> ?n ?mr)))
=>
	(modify ?max (maxr ?n) (indexr ?r))
)

(defrule check-max-col (declare (salience 20))
	?max <- (max_n (maxc ?mc) (indexc ?idxc))
	(k-per-col (col ?c) (num ?n&:(> ?n ?mc)))
=>
	(modify ?max (maxc ?n) (indexc ?c))
)

;mette content water in tutte le celle sulle righe con 0 navi all'interno
(defrule set_water_rows  (declare (salience 20))
	(k-per-row (row ?r) (num ?n))
	(test(= ?n 0))
	?cell <- (my-cell (x ?r) (y ?y) (content unknown) )
=>
	(modify ?cell (content water))
)

;mette content water in tutte le celle sulle colonne con 0 navi all'interno
(defrule set_water_cols (declare (salience 20))
	(k-per-col (col ?c) (num ?n))
	(test(= ?n 0))
	?cell <- (my-cell (x ?x) (y ?c) (content unknown) )
=>
	(modify ?cell (content water))
)

(defrule add-water-from-known (declare (salience 20))
	(k-cell (x ?x) (y ?y) (content water))
	?cell <- (my-cell (x ?x) (y ?y) (content unknown) )
=>
	(modify ?cell (content water))
	(printout t "added water in [" ?x ", " ?y "]" crlf)
)

(defrule add-next-guess-from-middle-col (declare (salience 5))
	(k-cell (x ?x)(y ?y)(content middle))
	(k-per-col (col ?y) (num ?nc&:(> ?nc 1)))
	?cell_up <- (my-cell (x ?x_up&:(eq ?x_up (+ ?x 1))) (y ?y) (content unknown))
	?cell_down <- (my-cell (x ?x_down&:(eq ?x_down (- ?x 1)))(y ?y) (content unknown))
=>
	(modify ?cell_up (content next-guess))
	(modify ?cell_down (content next-guess))
	(printout t "added next-guess-col in [" ?x_up ", " ?y "]" crlf)
	(printout t "added next-guess-col in [" ?x_down ", " ?y "]" crlf)
)

(defrule add-next-guess-from-middle-row (declare (salience 5))
	(k-cell (x ?x)(y ?y)(content middle))
	(k-per-row (row ?x) (num ?nr&:(> ?nr 1)))
	?cell_left <- (my-cell (x ?x) (y ?y_left&:(eq ?y_left (- ?y 1))) (content unknown))
	?cell_right <- (my-cell (x ?x) (y ?y_right&:(eq ?y_right (+ ?y 1))) (content unknown))
=>
	(modify ?cell_left (content next-guess))
	(modify ?cell_right (content next-guess))
	(printout t "added next-guess-row in [" ?x ", " ?y_left "]" crlf)
	(printout t "added next-guess-row in [" ?x ", " ?y_right "]" crlf)
)

(defrule add-water-to-bottom (declare (salience 20))
	?my_cell <- (my-cell (x ?x)(y ?y)(content unknown))
	(k-cell (x ?x_down&:(eq ?x_down (- ?x 1)))(y ?y)(content bot | left | right | sub))
=>
	(modify ?my_cell (content water))
	(printout t "added water to bottom in [" ?x ", " ?y "]" crlf)
)

(defrule add-water-to-top (declare (salience 20))
	?my_cell <- (my-cell (x ?x)(y ?y)(content unknown))
	(k-cell (x ?x_up&:(eq ?x_up (+ ?x 1)))(y ?y)(content top | left | right | sub))
=>
	(modify ?my_cell (content water))
	(printout t "added water to top in [" ?x ", " ?y "]" crlf)
)

(defrule add-water-to-left (declare (salience 20))
	?my_cell <- (my-cell (x ?x)(y ?y)(content unknown))
	(k-cell (x ?x)(y ?y_right&:(eq ?y_right (+ ?y 1)))(content top | bot | left | sub))
=>
	(modify ?my_cell (content water))
	(printout t "added water to left in [" ?x ", " ?y "]" crlf)
)

(defrule add-water-to-right (declare (salience 20))
	?my_cell <- (my-cell (x ?x)(y ?y)(content unknown))
	(k-cell (x ?x)(y ?y_left&:(eq ?y_left (- ?y 1)))(content top | bot | right | sub))
=>
	(modify ?my_cell (content water))
	(printout t "added water to right in [" ?x ", " ?y "]" crlf)
)
; ------------------------------ GUESS ------------------------------
(defrule guess-known (declare (salience 10))
	(status (step ?s)(currently running))
	(k-cell (x ?x)(y ?y)(content bot | middle | top | left | right))
	?max <- (max_n (indexr ?idx) (indexc ?idy))
	?act <- (n_actions (n_guess ?ng))
	?cell <- (my-cell (x ?x) (y ?y) (content unknown) )
	?nrow <- (k-per-row (row ?x) (num ?nr))
	?ncol <- (k-per-col (col ?y) (num ?nc))
	(not (exec  (action guess) (x ?x) (y ?y)))
=>
	(assert (exec (step ?s) (action guess) (x ?x) (y ?y)))
	(modify ?cell (content boat) )
	(modify ?max (maxr 0) (indexr 0) (maxc 0) (indexc 0))
	(bind ?ng (+ ?ng 1))
	(modify ?act (n_guess ?ng))
	(bind ?nr (- ?nr 1))
	(modify ?nrow (num ?nr))
	(bind ?nc (- ?nc 1))
	(modify ?ncol (num ?nc))
	
	(printout t "guess-known in pos [" ?x ", " ?y "] at step" ?s  crlf)
    (pop-focus)
)

(defrule guess-known-sub (declare (salience 10))
	(status (step ?s)(currently running))
	(k-cell (x ?x)(y ?y)(content sub))
	?max <- (max_n (indexr ?idx) (indexc ?idy))
	?act <- (n_actions (n_guess ?ng))
	?cell <- (my-cell (x ?x) (y ?y) (content unknown) )
	?nrow <- (k-per-row (row ?x) (num ?nr))
	?ncol <- (k-per-col (col ?y) (num ?nc))
	(not (exec  (action guess) (x ?x) (y ?y)))
=>
	(assert (exec (step ?s) (action guess) (x ?x) (y ?y)))
	
	(modify ?cell (content boat) )	
	(modify ?max (maxr 0) (indexr 0) (maxc 0) (indexc 0))
	(bind ?ng (+ ?ng 1))
	(modify ?act (n_guess ?ng))
	(bind ?nr (- ?nr 1))
	(modify ?nrow (num ?nr))
	(bind ?nc (- ?nc 1))
	(modify ?ncol (num ?nc))
	
	(printout t "guess-known-sub in pos [" ?x ", " ?y "] at step" ?s  crlf)
    (pop-focus)
)

(defrule guess-from-known-bot (declare (salience 10))
	(status (step ?s)(currently running))
	(k-cell (x ?x)(y ?y)(content bot))
	?max <- (max_n (indexr ?idx) (indexc ?idy))
	?act <- (n_actions (n_guess ?ng))
	?cell <- (my-cell (x = (- ?x 1)) (y ?y) (content unknown) )
	?nrow <- (k-per-row (row = (- ?x 1)) (num ?nr))
	?ncol <- (k-per-col (col ?y) (num ?nc))
	(not (exec (action guess) (x = (- ?x 1)) (y ?y)))
=>
	(bind ?x (- ?x 1))
	(assert (exec (step ?s) (action guess) (x ?x) (y ?y)))
	(modify ?cell (content boat) )
	(modify ?max (maxr 0) (indexr 0) (maxc 0) (indexc 0))
	(bind ?ng (+ ?ng 1))
	(modify ?act (n_guess ?ng))
	(bind ?nr (- ?nr 1))
	(modify ?nrow (num ?nr))
	(bind ?nc (- ?nc 1))
	(modify ?ncol (num ?nc))
	
	(printout t "guess-from-bot in pos [" ?x ", " ?y "] at step " ?s  crlf)
    (pop-focus)
)

(defrule guess-from-known-top (declare (salience 10))
	(status (step ?s)(currently running))
	(k-cell (x ?x)(y ?y)(content top))
	?max <- (max_n (indexr ?idx) (indexc ?idy))
	?act <- (n_actions (n_guess ?ng))
	?cell <- (my-cell (x = (+ ?x 1)) (y ?y) (content unknown) )
	?nrow <- (k-per-row (row = (+ ?x 1)) (num ?nr))
	?ncol <- (k-per-col (col ?y) (num ?nc))
	(not (exec (action guess) (x = (+ ?x 1)) (y ?y)))
=>
	(bind ?x (+ ?x 1))
	(assert (exec (step ?s) (action guess) (x ?x) (y ?y)))
	(modify ?cell (content boat) )
	(modify ?max (maxr 0) (indexr 0) (maxc 0) (indexc 0))
	(bind ?ng (+ ?ng 1))
	(modify ?act (n_guess ?ng))
	(bind ?nr (- ?nr 1))
	(modify ?nrow (num ?nr))
	(bind ?nc (- ?nc 1))
	(modify ?ncol (num ?nc))
	
	(printout t "guess-from-top in pos [" ?x ", " ?y "] at step " ?s  crlf)
    (pop-focus)
)

(defrule guess-from-known-left (declare (salience 10))
	(status (step ?s)(currently running))
	(k-cell (x ?x)(y ?y)(content left))
	?max <- (max_n (indexr ?idx) (indexc ?idy))
	?act <- (n_actions (n_guess ?ng))
	?cell <- (my-cell (x ?x) (y = (+ ?y 1)) (content unknown) )
	?nrow <- (k-per-row (row ?x) (num ?nr))
	?ncol <- (k-per-col (col = (+ ?y 1)) (num ?nc))
	(not (exec (action guess) (x ?x) (y = (+ ?y 1))))
=>
	(bind ?y (+ ?y 1))
	(assert (exec (step ?s) (action guess) (x ?x) (y ?y)))
	(modify ?cell (content boat) )
	(modify ?max (maxr 0) (indexr 0) (maxc 0) (indexc 0))
	(bind ?ng (+ ?ng 1))
	(modify ?act (n_guess ?ng))
	(bind ?nr (- ?nr 1))
	(modify ?nrow (num ?nr))
	(bind ?nc (- ?nc 1))
	(modify ?ncol (num ?nc))
	
	(printout t "guess-from-left in pos [" ?x ", " ?y "] at step " ?s  crlf)
    (pop-focus)
)

(defrule guess-from-known-right (declare (salience 10))
	(status (step ?s)(currently running))
	(k-cell (x ?x)(y ?y)(content right))
	?max <- (max_n (indexr ?idx) (indexc ?idy))
	?act <- (n_actions (n_guess ?ng))
	?cell <- (my-cell (x ?x) (y = (- ?y 1)) (content unknown) )
	?nrow <- (k-per-row (row ?x) (num ?nr))
	?ncol <- (k-per-col (col = (- ?y 1)) (num ?nc))
	(not (exec (action guess) (x ?x) (y = (- ?y 1))))
=>
	(bind ?y (- ?y 1))
	(assert (exec (step ?s) (action guess) (x ?x) (y ?y)))
	(modify ?cell (content boat) )
	(modify ?max (maxr 0) (indexr 0) (maxc 0) (indexc 0))
	(bind ?ng (+ ?ng 1))
	(modify ?act (n_guess ?ng))
	(bind ?nr (- ?nr 1))
	(modify ?nrow (num ?nr))
	(bind ?nc (- ?nc 1))
	(modify ?ncol (num ?nc))
	
	(printout t "guess-from-right in pos [" ?x ", " ?y "] at step " ?s  crlf)
    (pop-focus)
)

(defrule guess-down-from-known-middle (declare (salience 10))
	(status (step ?s)(currently running))
	(k-cell (x ?x)(y ?y)(content middle))
	?max <- (max_n (indexr ?idx) (indexc ?idy))
	?act <- (n_actions (n_guess ?ng))
	?parent <- (my-cell (x = (- ?x 1))(y ?y))
	?child <- (my-cell (x = (+ ?x 1)) (y ?y) (content unknown) )
	?nrow <- (k-per-row (row =(+ ?x 1)) (num ?nr))
	?ncol <- (k-per-col (col ?y) (num ?nc))
	(not (exec (action guess) (x = (+ ?x 1)) (y ?y)))
=>
	(bind ?x (+ ?x 1))
	(assert (exec (step ?s) (action guess) (x ?x) (y ?y)))
	(modify ?child (content boat) )
	(modify ?max (maxr 0) (indexr 0) (maxc 0) (indexc 0))
	(bind ?ng (+ ?ng 1))
	(modify ?act (n_guess ?ng))
	(bind ?nr (- ?nr 1))
	(modify ?nrow (num ?nr))
	(bind ?nc (- ?nc 1))
	(modify ?ncol (num ?nc))
	
	(printout t "guess-down-from-middle in pos [" ?x ", " ?y "] at step " ?s  crlf)
    (pop-focus)
)

(defrule guess-up-from-known-middle (declare (salience 10))
	(status (step ?s)(currently running))
	(k-cell (x ?x)(y ?y)(content middle))
	?max <- (max_n (indexr ?idx) (indexc ?idy))
	?act <- (n_actions (n_guess ?ng))
	?parent <- (my-cell (x = (+ ?x 1))(y ?y))
	?child <- (my-cell (x = (- ?x 1)) (y ?y) (content unknown) )
	?nrow <- (k-per-row (row =(- ?x 1)) (num ?nr))
	?ncol <- (k-per-col (col ?y) (num ?nc))
	(not (exec (action guess) (x = (- ?x 1)) (y ?y)))
=>
	(bind ?x (- ?x 1))
	(assert (exec (step ?s) (action guess) (x ?x) (y ?y)))
	(modify ?child (content boat) )
	(modify ?max (maxr 0) (indexr 0) (maxc 0) (indexc 0))
	(bind ?ng (+ ?ng 1))
	(modify ?act (n_guess ?ng))	
	(bind ?nr (- ?nr 1))
	(modify ?nrow (num ?nr))
	(bind ?nc (- ?nc 1))
	(modify ?ncol (num ?nc))
	
	(printout t "guess-up-from-middle in pos [" ?x ", " ?y "] at step " ?s  crlf)
    (pop-focus)
)

(defrule guess-left-from-known-middle (declare (salience 10))
	(status (step ?s)(currently running))
	(k-cell (x ?x)(y ?y)(content middle))
	?max <- (max_n (indexr ?idx) (indexc ?idy))
	?act <- (n_actions (n_guess ?ng))
	?parent <- (my-cell (x ?x)(y = (+ ?y 1))(content boat))
	?child <- (my-cell (x ?x) (y = (- ?y 1)) (content unknown) )
	?nrow <- (k-per-row (row ?x) (num ?nr))
	?ncol <- (k-per-col (col = (- ?y 1)) (num ?nc))
	(not (exec (action guess) (x ?x) (y = (- ?y 1))))
=>
	(bind ?y (- ?y 1))
	(assert (exec (step ?s) (action guess) (x ?x) (y ?y)))
	(modify ?child (content boat) )
	(modify ?max (maxr 0) (indexr 0) (maxc 0) (indexc 0))
	(bind ?ng (+ ?ng 1))
	(modify ?act (n_guess ?ng))	
	(bind ?nr (- ?nr 1))
	(modify ?nrow (num ?nr))
	(bind ?nc (- ?nc 1))
	(modify ?ncol (num ?nc))
	
	(printout t "guess-left-from-middle in pos [" ?x ", " ?y "] at step " ?s  crlf)
    (pop-focus)
)

(defrule guess-right-from-known-middle (declare (salience 10))
	(status (step ?s)(currently running))
	(k-cell (x ?x)(y ?y)(content middle))
	?max <- (max_n (indexr ?idx) (indexc ?idy))
	?act <- (n_actions (n_guess ?ng))
	?parent <- (my-cell (x ?x)(y = (- ?y 1))(content boat))
	?child <- (my-cell (x ?x) (y = (+ ?y 1)) (content unknown) )
	?nrow <- (k-per-row (row ?x) (num ?nr))
	?ncol <- (k-per-col (col = (+ ?y 1)) (num ?nc))
	(not (exec (action guess) (x ?x) (y = (+ ?y 1))))
=>
	(bind ?y (+ ?y 1))
	(assert (exec (step ?s) (action guess) (x ?x) (y ?y)))
	(modify ?child (content boat) )
	(modify ?max (maxr 0) (indexr 0) (maxc 0) (indexc 0))
	(bind ?ng (+ ?ng 1))
	(modify ?act (n_guess ?ng))	
	(bind ?nr (- ?nr 1))
	(modify ?nrow (num ?nr))
	(bind ?nc (- ?nc 1))
	(modify ?ncol (num ?nc))
	
	(printout t "guess-right-from-middle in pos [" ?x ", " ?y "] at step " ?s  crlf)
    (pop-focus)
)

(defrule guess-from-next-guess (declare (salience 5))
	(status (step ?s)(currently running))
	?cell <- (my-cell (x ?x) (y ?y) (content next-guess))
	?max <- (max_n (indexr ?idx) (indexc ?idy))
	?act <- (n_actions (n_guess ?ng))
	?nrow <- (k-per-row (row ?x) (num ?nr))
	?ncol <- (k-per-col (col ?y) (num ?nc))
	(not (exec  (action guess) (x ?x) (y ?y)))
=>
	(assert (exec (step ?s) (action guess) (x ?x) (y ?y)))
	(modify ?cell (content boat) )
	(modify ?max (maxr 0) (indexr 0) (maxc 0) (indexc 0))
	(bind ?ng (+ ?ng 1))
	(modify ?act (n_guess ?ng))
	(bind ?nr (- ?nr 1))
	(modify ?nrow (num ?nr))
	(bind ?nc (- ?nc 1))
	(modify ?ncol (num ?nc))
	
	(printout t "guess-from-next-guess in pos [" ?x ", " ?y "] at step" ?s  crlf)
    (pop-focus)
)
; ------------------------------ FIRE ------------------------------
(defrule fire-down-from-known-top (declare (salience 5))
	(status (step ?s)(currently running))
	?act <- (n_actions (n_fire ?nf&:(< ?nf 5)))
	(k-cell (x ?x)(y ?y)(content top))
	(my-cell (x = (+ ?x 2)) (y ?y) (content unknown) )
	(not (exec (action fire|guess) (x = (+ ?x 2)) (y ?y)))
=>
	(bind ?nf (+ ?nf 1))
	(modify ?act (n_fire ?nf))
	(bind ?x (+ ?x 2)) 
	(assert (exec (step ?s) (action fire) (x ?x) (y ?y)))
	
	(printout t "fire-down-from-top in pos [" ?x ", " ?y "] at step " ?s crlf)
	(pop-focus)
)

(defrule fire-up-from-known-bot (declare (salience 5))
	(status (step ?s)(currently running))
	?act <- (n_actions (n_fire ?nf&:(< ?nf 5)))
	(k-cell (x ?x)(y ?y)(content bot))
	(my-cell (x = (- ?x 2)) (y ?y) (content unknown) )
	(not (exec (action fire|guess) (x = (- ?x 2)) (y ?y)))
=>
	(bind ?nf (+ ?nf 1))
	(modify ?act (n_fire ?nf))
	(bind ?x (- ?x 2)) 
	(assert (exec (step ?s) (action fire) (x ?x) (y ?y)))
	
	(printout t "fire-up-from-bot in pos [" ?x ", " ?y "] at step " ?s crlf)
	(pop-focus)
)

(defrule fire-left-from-known-right (declare (salience 5))
	(status (step ?s)(currently running))
	?act <- (n_actions (n_fire ?nf&:(< ?nf 5)))
	(k-cell (x ?x)(y ?y)(content right))
	(my-cell (x ?x) (y = (- ?y 2)) (content unknown) )
	(not (exec (action fire|guess) (x ?x) (y = (- ?y 2))))
=>
	(bind ?nf (+ ?nf 1))
	(modify ?act (n_fire ?nf))
	(bind ?y (- ?y 2)) 
	(assert (exec (step ?s) (action fire) (x ?x) (y ?y)))
	
	(printout t "fire-left-from-right in pos [" ?x ", " ?y "] at step " ?s crlf)
	(pop-focus)
)

(defrule fire-right-from-known-left (declare (salience 5))
	(status (step ?s)(currently running))
	?act <- (n_actions (n_fire ?nf&:(< ?nf 5)))
	(k-cell (x ?x)(y ?y)(content right))
	(my-cell (x ?x) (y = (+ ?y 2)) (content unknown) )
	(not (exec (action fire|guess) (x ?x) (y = (+ ?y 2))))
=>
	(bind ?nf (+ ?nf 1))
	(modify ?act (n_fire ?nf))
	(bind ?y (+ ?y 2)) 
	(assert (exec (step ?s) (action fire) (x ?x) (y ?y)))
	
	(printout t "fire-right-from-left in pos [" ?x ", " ?y "] at step " ?s crlf)
	(pop-focus)
)

(defrule fire-most-likelihood-cell (declare (salience 5))
    ?max <- (max_n (indexr ?x) (indexc ?y))
	?act <- (n_actions (n_fire ?nf&:(< ?nf 5)))
    (status (step ?s)(currently running))
    (my-cell (x ?x) (y ?y) (content unknown) )
    (not (exec (action fire|guess) (x ?x) (y ?y)))
=>
	(bind ?nf (+ ?nf 1))
	(modify ?act (n_fire ?nf))
    (assert (exec (step ?s) (action fire) (x ?x) (y ?y)))
    (modify ?max (maxr 0) (indexr 0) (maxc 0) (indexc 0))
    (printout t "fire-most-likelihood in pos [" ?x ", " ?y "] at step " ?s crlf)
    (pop-focus)
)

; ------------------------------ SOLVE ------------------------------

(defrule solve-when-put-all-guess (declare (salience 40))
	(status (step ?s)(currently running))
	(n_actions (n_guess ?n&:(> ?n 19)))
=>
	(assert (exec (step ?s) (action solve)))
	(printout t "solve" crlf)
	(pop-focus)
)

(defrule guess-most-likelihood-cell 
    ?max <- (max_n (indexr ?x) (indexc ?y))
	?act <- (n_actions (n_guess ?ng))
    (status (step ?s)(currently running))
    (my-cell (x ?x) (y ?y) (content ~water))
	?nrow <- (k-per-row (row ?x) (num ?nr))
	?ncol <- (k-per-col (col ?y) (num ?nc))
    (not (exec (action guess) (x ?x) (y ?y)))
=>
    (assert (exec (step ?s) (action guess) (x ?x) (y ?y)))
	(modify ?max (maxr 0) (indexr 0) (maxc 0) (indexc 0))
	(bind ?ng (+ ?ng 1))
	(modify ?act (n_guess ?ng))	
	(bind ?nr (- ?nr 1))
	(modify ?nrow (num ?nr))
	(bind ?nc (- ?nc 1))
	(modify ?ncol (num ?nc))
    (printout t "guess-most-likelihood in pos [" ?x ", " ?y "] at step " ?s crlf)
    (pop-focus)
)

(defrule guess-what-remains
	(status (step ?s)(currently running))
	?act <- (n_actions (n_guess ?ng))
	(my-cell (x ?x) (y ?y) (content ~water))
	?nrow <- (k-per-row (row ?x) (num ?nr))
	?ncol <- (k-per-col (col ?y) (num ?nc))
	(not (exec (action guess) (x ?x) (y ?y)))
=>
	(assert (exec (step ?s) (action guess) (x ?x) (y ?y)))
	(bind ?ng (+ ?ng 1))
	(modify ?act (n_guess ?ng))
	(bind ?nr (- ?nr 1))
	(modify ?nrow (num ?nr))
	(bind ?nc (- ?nc 1))
	(modify ?ncol (num ?nc))
    (printout t "guess-what-remains in pos [" ?x ", " ?y "] at step " ?s crlf)
    (pop-focus)
)
